site_name: SnakeMaker lib documentation

nav:
  - Home: index.md
  - Configuration: configuration.md
  - Rule configuration: rule_configuration.md
  - Snakefile configuration: snakefile_configuration.md
  - Examples: examples.md
  - Changelog: changelog.md

theme:
  name: readthedocs